//     Beard.js
//
//     The MIT License (MIT)
//     Copyright (c) 2013 NextUser
(function (undefined) {
    "use strict";
    var Beard;
    // Constructor
    // ------------------
    // Parameters:
    //
    // * `tpl` - Template
    // * `data` - Data
    // * `elements` - Elements
    //
    //
    //     var beard = new Beard(tpl, data, elements);
    //
    Beard = function (tpl, data, elements) {
        this.tpl = tpl || '';
        this.dat = data || {};
        this.UDEF = undefined;
        this.elements = elements || {};
    };
Beard.prototype = {
    // Set the template
    set: function (tpl) {
        this.tpl = tpl || '';
        return this;
    },
    // Get the template
    get: function () {
        return this.tpl;
    },
    // Render the template
    render: function (data) {
        if (data) {
            this.dat = data;
        }
        return Beard.compile(this.tpl, {elements: this.elements, variables: this.dat});
    },
    // Returns an object containing an array of variables, and an array of elements:
    getRequired: function (tpl) {
        // TODO: Use Parser
    },
    // Add many template elements
    addElements: function (elements) {
        var k;
        for (k in elements) {
            if (elements.hasOwnProperty(k)) {
                this.elements[k] = elements[k];
            }
        }
        return this;
    },
    // Add a template element
    addElement: function (id, element) {
        this.elements[id] = element;
        return this;
    },
    // Remove a template element
    remElement: function (id) {
        delete this.elements[id];
        return this;
    },
    // Remove all elements
    remElements: function () {
        this.elements = {};
        return this;
    },
    // Add some data in the data object (may be a variable, a function)
    addVariable: function (key, value) {
        this.dat[key] = value;
        return this;
    },
    // Remove some data in the data object
    remVariable: function (key) {
        delete this.dat[key];
        return this;
    },
    // Remove everything in the data object
    // FIXME: Change name?
    resetDataObject: function () {
        this.dat = {};
        return this;
    }
};
    // Beard.Parser
    // ------------
/* parser generated by jison 0.4.13 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"root":3,"statements":4,"EOF":5,"program":6,"simpleInverse":7,"OPEN_INVERSE":8,"CLOSE":9,"statement":10,"openBlock":11,"closeBlock":12,"elementTag":13,"variableTag":14,"CONTENT":15,"COMMENT":16,"OPEN":17,"ID":18,"segments":19,"hash":20,"hashSegment":21,"EQUALS":22,"param":23,"END_BLOCK":24,"OPEN_ELEMENT":25,"OPEN_VARIABLE":26,"var":27,"func":28,"ALT":29,"SEP":30,"OP":31,"args":32,"CP":33,"COMMA":34,"STRING":35,"INTEGER":36,"BOOLEAN":37,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:"OPEN_INVERSE",9:"CLOSE",15:"CONTENT",16:"COMMENT",17:"OPEN",18:"ID",22:"EQUALS",24:"END_BLOCK",25:"OPEN_ELEMENT",26:"OPEN_VARIABLE",29:"ALT",30:"SEP",31:"OP",33:"CP",34:"COMMA",35:"STRING",36:"INTEGER",37:"BOOLEAN"},
productions_: [0,[3,2],[6,2],[6,3],[6,2],[6,1],[6,1],[6,0],[7,2],[4,1],[4,2],[10,3],[10,1],[10,1],[10,1],[10,1],[11,4],[11,4],[20,1],[21,3],[12,1],[13,3],[14,3],[14,3],[27,1],[27,3],[27,3],[27,5],[28,4],[28,6],[28,6],[28,8],[19,3],[19,1],[32,3],[32,1],[32,0],[23,1],[23,1],[23,1],[23,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */
var $0 = $$.length - 1;
switch (yystate) {
case 1: return new yy.ProgramNode($$[$0-1]);
break;
case 2:this.$ = new yy.ProgramNode([], $$[$0]);
break;
case 3:this.$ = new yy.ProgramNode($$[$0-2], $$[$0]);
break;
case 4:this.$ = new yy.ProgramNode($$[$0-1], []);
break;
case 5:this.$ = new yy.ProgramNode($$[$0]);
break;
case 6:this.$ = new yy.ProgramNode([]);
break;
case 7:this.$ = new yy.ProgramNode([]);
break;
case 9:this.$ = [$$[$0]];
break;
case 10: $$[$0-1].push($$[$0]); this.$ = $$[$0-1];
break;
case 11:this.$ = new yy.BlockNode($$[$0-2], $$[$0-1], $$[$0]);
break;
case 12:this.$ = new yy.ElementNode($$[$0]);
break;
case 13:this.$ = $$[$0];
break;
case 14:this.$ = new yy.ContentNode($$[$0]);
break;
case 15:this.$ = new yy.CommentNode($$[$0]);
break;
case 16:this.$ = [$$[$0-2], new yy.DataNode($$[$0-1])];
break;
case 17:this.$ = [$$[$0-2], $$[$0-1]];
break;
case 18:this.$ = new yy.HashNode($$[$0]);
break;
case 19:this.$ = [new yy.DataNode($$[$0-2]), $$[$0]];
break;
case 20:this.$ = $$[$0];
break;
case 21:this.$ = $$[$0-1];
break;
case 22:this.$ = $$[$0-1];
break;
case 23:this.$ = $$[$0-1];
break;
case 24:this.$ = new yy.DataNode($$[$0]);
break;
case 25:this.$ = new yy.DataNode($$[$0-2], $$[$0]);
break;
case 26:this.$ = new yy.DataNode([$$[$0-2]].concat($$[$0]));
break;
case 27:this.$ = new yy.DataNode([$$[$0-4]].concat($$[$0-2]), $$[$0]);
break;
case 28:this.$ = new yy.FuncNode($$[$0-3], $$[$0-1]);
break;
case 29:this.$ = new yy.FuncNode($$[$0-5], $$[$0-3], $$[$0]);
break;
case 30:this.$ = new yy.FuncNode([$$[$0-5]].concat($$[$0-3]), $$[$0-1]);
break;
case 31:this.$ = new yy.FuncNode([$$[$0-7]].concat($$[$0-5]), $$[$0-3], $$[$0]);
break;
case 32: $$[$0-2].push($$[$0]); this.$ = $$[$0-2];
break;
case 33:this.$ = [$$[$0]];
break;
case 34: $$[$0-2].push($$[$0]); this.$ = $$[$0-2];
break;
case 35:this.$ = [$$[$0]];
break;
case 36:this.$ = [];
break;
case 37:this.$ = new yy.StringNode($$[$0]);
break;
case 38:this.$ = new yy.IntegerNode($$[$0]);
break;
case 39:this.$ = new yy.BooleanNode($$[$0]);
break;
case 40:this.$ = new yy.IdNode($$[$0]);
break;
}
},
table: [{3:1,4:2,10:3,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],25:[1,10],26:[1,11]},{1:[3]},{5:[1,12],10:13,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],25:[1,10],26:[1,11]},{5:[2,9],8:[2,9],15:[2,9],16:[2,9],17:[2,9],24:[2,9],25:[2,9],26:[2,9]},{4:16,6:14,7:15,8:[1,17],10:3,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],24:[2,7],25:[1,10],26:[1,11]},{5:[2,12],8:[2,12],15:[2,12],16:[2,12],17:[2,12],24:[2,12],25:[2,12],26:[2,12]},{5:[2,13],8:[2,13],15:[2,13],16:[2,13],17:[2,13],24:[2,13],25:[2,13],26:[2,13]},{5:[2,14],8:[2,14],15:[2,14],16:[2,14],17:[2,14],24:[2,14],25:[2,14],26:[2,14]},{5:[2,15],8:[2,15],15:[2,15],16:[2,15],17:[2,15],24:[2,15],25:[2,15],26:[2,15]},{18:[1,18]},{18:[1,19]},{18:[1,23],19:22,27:20,28:21},{1:[2,1]},{5:[2,10],8:[2,10],15:[2,10],16:[2,10],17:[2,10],24:[2,10],25:[2,10],26:[2,10]},{12:24,24:[1,25]},{4:26,10:3,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],24:[2,6],25:[1,10],26:[1,11]},{7:27,8:[1,17],10:13,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],24:[2,5],25:[1,10],26:[1,11]},{9:[1,28]},{18:[1,23],19:29,20:30,21:31},{9:[1,32]},{9:[1,33]},{9:[1,34],30:[1,35]},{9:[2,24],29:[1,36],30:[1,38],31:[1,37]},{9:[2,33],22:[2,33],29:[2,33],30:[2,33],31:[2,33]},{5:[2,11],8:[2,11],15:[2,11],16:[2,11],17:[2,11],24:[2,11],25:[2,11],26:[2,11]},{5:[2,20],8:[2,20],15:[2,20],16:[2,20],17:[2,20],24:[2,20],25:[2,20],26:[2,20]},{10:13,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],24:[2,2],25:[1,10],26:[1,11]},{4:39,10:3,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],24:[2,4],25:[1,10],26:[1,11]},{15:[2,8],16:[2,8],17:[2,8],24:[2,8],25:[2,8],26:[2,8]},{9:[1,40],22:[1,41],30:[1,38]},{9:[1,42]},{9:[2,18]},{5:[2,21],8:[2,21],15:[2,21],16:[2,21],17:[2,21],24:[2,21],25:[2,21],26:[2,21]},{5:[2,22],8:[2,22],15:[2,22],16:[2,22],17:[2,22],24:[2,22],25:[2,22],26:[2,22]},{5:[2,23],8:[2,23],15:[2,23],16:[2,23],17:[2,23],24:[2,23],25:[2,23],26:[2,23]},{18:[1,23],19:43},{18:[1,48],23:44,35:[1,45],36:[1,46],37:[1,47]},{18:[1,48],23:50,32:49,33:[2,36],34:[2,36],35:[1,45],36:[1,46],37:[1,47]},{18:[1,51]},{10:13,11:4,13:5,14:6,15:[1,7],16:[1,8],17:[1,9],24:[2,3],25:[1,10],26:[1,11]},{8:[2,16],15:[2,16],16:[2,16],17:[2,16],24:[2,16],25:[2,16],26:[2,16]},{18:[1,48],23:52,35:[1,45],36:[1,46],37:[1,47]},{8:[2,17],15:[2,17],16:[2,17],17:[2,17],24:[2,17],25:[2,17],26:[2,17]},{9:[2,26],29:[1,53],30:[1,38],31:[1,54]},{9:[2,25]},{9:[2,37],30:[2,37],33:[2,37],34:[2,37]},{9:[2,38],30:[2,38],33:[2,38],34:[2,38]},{9:[2,39],30:[2,39],33:[2,39],34:[2,39]},{9:[2,40],30:[2,40],33:[2,40],34:[2,40]},{33:[1,55],34:[1,56]},{33:[2,35],34:[2,35]},{9:[2,32],22:[2,32],29:[2,32],30:[2,32],31:[2,32]},{9:[2,19]},{18:[1,48],23:57,35:[1,45],36:[1,46],37:[1,47]},{18:[1,48],23:50,32:58,33:[2,36],34:[2,36],35:[1,45],36:[1,46],37:[1,47]},{9:[2,28],29:[1,59],30:[2,28]},{18:[1,48],23:60,35:[1,45],36:[1,46],37:[1,47]},{9:[2,27]},{33:[1,61],34:[1,56]},{18:[1,48],23:62,35:[1,45],36:[1,46],37:[1,47]},{33:[2,34],34:[2,34]},{9:[2,30],29:[1,63],30:[2,30]},{9:[2,29],30:[2,29]},{18:[1,48],23:64,35:[1,45],36:[1,46],37:[1,47]},{9:[2,31],30:[2,31]}],
defaultActions: {12:[2,1],31:[2,18],44:[2,25],52:[2,19],57:[2,27]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == 'undefined') {
        this.lexer.yylloc = {};
    }
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === 'function') {
        this.parseError = this.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || EOF;
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (this.lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + this.lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: this.lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: this.lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                this.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.2.1 */
var lexer = (function(){
var lexer = {
EOF:1,
parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },
// resets the lexer, sets new input
setInput:function (input) {
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },
// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }
        this._input = this._input.slice(1);
        return ch;
    },
// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);
        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len - 1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);
        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;
        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };
        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },
// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },
// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
        return this;
    },
// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },
// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },
// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },
// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },
// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;
        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }
        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },
// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }
        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },
// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },
// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },
// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },
// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },
// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },
// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },
// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
function strip (start, end) {
    return yy_.yytext = yy_.yytext.substr(start, yy_.yyleng-end);
}
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:
                                                this.begin('beard');
                                                if (yy_.yytext) return 15;
break;
case 1:return 15;
break;
case 2:strip(0,2); this.popState(); return 16;
break;
case 3:return 26;
break;
case 4:return 25;
break;
case 5:this.popState(); this.begin('com');
break;
case 6:strip(3,5); this.popState(); return 16;
break;
case 7:strip(6,9); this.popState(); return 24;
break;
case 8:return 8;
break;
case 9:return 17;
break;
case 10:return 29;
break;
case 11:return 30;
break;
case 12:return 34;
break;
case 13:return 31;
break;
case 14:return 33;
break;
case 15:return 22;
break;
case 16:/* ignore whitespace */
break;
case 17:this.popState(); return 9;
break;
case 18:yy_.yytext = strip(1,2).replace(/\\"/g,'"'); return 35;
break;
case 19:yy_.yytext = strip(1,2).replace(/\\'/g,"'"); return 35;
break;
case 20:return 36;
break;
case 21:return 37;
break;
case 22:return 37;
break;
case 23:return 18;
break;
case 24:return 'INVALID';
break;
case 25:return 5;
break;
}
},
rules: [/^(?:[^\x00]*?(?=(<%)))/,/^(?:[^\x00]+)/,/^(?:[\s\S]*?%>)/,/^(?:<%=)/,/^(?:<%@)/,/^(?:<%#)/,/^(?:<%#[\s\S]*?%>)/,/^(?:<% end([a-zA-Z_][a-zA-Z0-9_]*) %>)/,/^(?:<%\s*else\b)/,/^(?:<%)/,/^(?:\|)/,/^(?:\.)/,/^(?:,)/,/^(?:\()/,/^(?:\))/,/^(?:=)/,/^(?:\s+)/,/^(?:%>)/,/^(?:"(\\["]|[^"])*")/,/^(?:'(\\[']|[^'])*')/,/^(?:-?[0-9]+)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:([a-zA-Z_][a-zA-Z0-9_]*))/,/^(?:.)/,/^(?:$)/],
conditions: {"beard":{"rules":[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],"inclusive":false},"com":{"rules":[2],"inclusive":false},"INITIAL":{"rules":[0,1,25],"inclusive":true}}
};
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();
    Beard.Parser = parser;
    // Beard.AST
    // ---------
Beard.AST = {};
Beard.AST.ProgramNode = function (statements, inverse) {
    this.type = 'program';
    this.statements = statements;
    if (inverse) {
        this.inverse = new Beard.AST.ProgramNode(inverse);
    }
};
Beard.AST.ElementNode = function (id) {
    this.type = 'element';
    this.id = id;
};
Beard.AST.ContentNode = function (string) {
    this.type = 'content';
    this.string = string;
};
Beard.AST.DataNode = function (variable, def) {
    this.type = 'data';
    this.variable = variable;
    this.def = def || '';
};
Beard.AST.CommentNode = function (comment) {
    this.type = 'comment';
    this.comment = comment;
};
Beard.AST.IdNode = function (id) {
    this.type = 'ID';
    this.id = id;
};
Beard.AST.BlockNode = function (helper, program, close) {
    if (helper[0] !== close) {
        throw new Error(helper[0] + " doesn't match " + close);
    }
    this.type = 'block';
    this.helper = helper;
    this.program = program;
};
Beard.AST.StringNode = function (string) {
    this.type = 'STRING';
    this.string = this.stringModeValue = string;
};
Beard.AST.FuncNode = function (func, args, def) {
    this.type = 'func';
    this.func = func;
    this.args = args;
    this.def = def;
};
Beard.AST.IntegerNode = function (integer) {
    this.type = 'INTEGER';
    this.integer = integer;
    this.stringModeValue = Number(integer);
};
Beard.AST.BooleanNode = function (bool) {
    this.type = 'BOOLEAN';
    this.bool = bool;
    this.stringModeValue = bool === 'true';
};
Beard.AST.HashNode = function (pairs) {
    this.type = 'hash';
    this.pairs = pairs;
};
    // Beard.Compiler
    // --------------
var Compiler = Beard.Compiler = function () {};
Compiler.prototype = {
    compiler: Compiler,
    compile: function (program, options) {
        var statements = program.statements,
            i = 0,
            l = statements.length,
            statement;
        options.elements = options.elements || {};
        options.variables = options.variables || {};
        this.options = options;
        this.result = [];
        for (i; i < l; i += 1) {
            statement = statements[i];
            console.log(statement);
            this.result.push(this[statement.type](statement));
        }
        return this;
    },
    // Compile element
    element: function (element) {
        if (this.options.elements[element.id]) {
            return Beard.evaluateElement(this.options.elements[element.id], this.options);
        }
        return "Element " + element.id + " not found";
    },
    // Compile content node
    content: function (string) {
        return string.string;
    },
    // Compile data variable tag
    data: function (data) {
        var i = 0,
            l = data.variable.length,
            v = this.options.variables,
            key;
        console.log('Compiler.data(): data:', data);
        for (; i < l; i += 1) {
            key = data.variable[i];
            // Handle Funciton-Variable mixture
            if (typeof key !== 'string' && key.constructor === Beard.AST.FuncNode) {
                v = this[key.type](key);
            } else {
                v = v[key];
            }
            if (typeof v === 'undefined') {
                if (data.def) {
                    v = this[data.def.type](data.def);
                } else {
                    v = '';
                }
                break;
            }
        }
        console.log('Compiler.data(): return value:', v);
        return v;
    },
    // Compile function call
    func: function (func) {
        var i = 0,
            l = func.func.length,
            parent,
            fn = parent = this.options.variables,
            key;
        for (; i < l; i += 1) {
            key = func.func[i];
            parent = fn;
            // Handle Funciton-Variable mixture
            if (typeof key !== 'string' && key.constructor === Beard.AST.FuncNode) {
                fn = this[key.type](key);
            } else {
                fn = fn[key];
            }
            if (typeof fn === 'undefined') {
                if (func.def) {
                    return this[func.def.type](func.def);
                }
                return;
            }
        }
        // `parent` is the function's `this`:
        //
        //     data = {
        //         first_name: 'John',
        //         last_name: 'Doe',
        //         full_name: function () {
        //             return this.first_name + ' ' + this.last_name;
        //             // return "John Doe"
        //         },
        //         nested: {
        //             first_name: 'Robert',
        //             last_name: 'Roe',
        //             full_name: function () {
        //                 return this.first_name + ' ' + this.last_name;
        //                 // return "Robert Roe"
        //             }
        //         }
        //     }
        return fn.apply(parent, this.args(func.args));
    },
    // Compile function's arguments
    args: function (args) {
        return args.map(function (v) {
            return this[v.type](v);
        }, this);
    },
    // Compile comment
    comment: function () {
        return '';
    },
    // Compile block instructions code
    block: function (block) {
        var helper,
            data,
            program;
        // Compile helper and its arguments or data
        data = block.helper.map(function (item) {
            if (typeof item !== 'string') {
                return this[item.type](item);
            }
            return item;
        }, this);
        helper = data[0];
        data = data[1];
        program = block.program;
        console.log('Compiler.block(): Helper:', helper, 'Arguments:', data, program, this.options);
        return Beard.BlockHelpers[helper](data, program, this.options);
    },
    // Compile hash
    hash: function (hash) {
        console.log('Compiler.hash():', hash);
        return hash.pairs.map(function (item) {
            if (typeof item !== 'string') {
                return this[item.type](item, true);
            }
            return item;
        }, this);
    },
    // Compile string parameter
    STRING: function (string) {
        return string.string;
    },
    // Compile integer parameter
    //
    // If `strict` is `True`, it returns the `Number` value,
    // otherwise, its `String` representation. The default is `False`.
    INTEGER: function (integer, strict) {
        strict = !!strict;
        return strict ? integer.stringModeValue : integer.integer;
    },
    // Compile boolean parameter
    //
    // If `strict` is `True`, it returns the `Boolean` value,
    // otherwise, its `String` representation. The default is `False`.
    BOOLEAN: function (bool, strict) {
        strict = !!strict;
        return strict ? bool.stringModeValue : bool.bool;
    }
};
    // Helpers
    // -------
Beard.BlockHelpers = Beard.Helpers = {};
Beard.registerHelper = function (name, func, is_block) {
    is_block = !!is_block;
    if (is_block) {
        Beard.BlockHelpers[name] = func;
    } else {
        Beard.Helpers[name] = func;
    }
};
// ### Core Helpers
Beard.registerHelper('foreach', function (data, program, options) {
    console.log('Helper FOREACH:', arguments);
    var key,
        value,
        l,
        program_options,
        env,
        result = [];
    data = data || {};
    // Iterate through the array
    if (data instanceof Array) {
        l = data.length;
        for (key = 0; key < l; key++) {
            program_options = options;
            value = data[key];
            program_options.variables.key = key;
            program_options.variables.value = value;
            env = new Compiler().compile(program, program_options);
            result = result.concat(env.result);
        }
    } else if (data instanceof Object) {
        for (key in data) {
            if (data.hasOwnProperty(key)) {
                value = data[key];
                program_options = options;
                value = data[key];
                program_options.variables.key = key;
                program_options.variables.value = value;
                env = new Compiler().compile(program, program_options);
                result = result.concat(env.result);
            }
        }
    } else {
        throw new Error('Data should be either Object or Array');
    }
    return result.join('');
}, true);
Beard.registerHelper('if', function (data, program, options) {
    console.log('Helper IF:', arguments);
    var env,
        result = [];
    if (data[0] == data[1]) {
        console.log('Helper IF: Positive test');
        env = new Compiler().compile(program, options);
        result = env.result;
    }
    return result.join('');
}, true);
    Beard.parse = function (input) {
        Beard.Parser.yy = Beard.AST;
        return Beard.Parser.parse(input);
    };
    Beard.compile = function (input, options) {
        options = options || {};
        var ast = Beard.parse(input),
            env = new Compiler().compile(ast, options);
        return env.result.join('');
    };
    Beard.evaluateElement = function (input, options) {
        return Beard.compile(input, options);
    };
    this.Beard = Beard;
}).call(this);
